/**
 * Prepares a card's HTML for the sandboxed frame.
 *
 * The card is generated by the gateway from text an upstream server
 * controls (sanitised there, and covered by its own XSS tests), and the
 * frame it runs in has an opaque origin (`sandbox="allow-scripts"`, no
 * `allow-same-origin`): it cannot read this page, its storage, or its
 * cookies. This adds one more layer that costs nothing: a
 * Content-Security-Policy that lets the card run its own inline script and
 * style and lets it do nothing else. No request of any kind can leave the
 * frame; the only way out is `postMessage` to this host, which the host
 * then filters (see ConsentCard.tsx).
 */
export const CARD_CSP = "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:";

export function withCsp(html: string): string {
  const tag = `<meta http-equiv="Content-Security-Policy" content="${CARD_CSP}">`;
  return html.includes("<head>") ? html.replace("<head>", () => `<head>${tag}`) : `${tag}${html}`;
}
